/*
 * AppConstants
 * These are the variables that determine what our central data store (reducer.js)
 * changes in our state. When you add a new action, you have to add a new constant here
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'YOUR_ACTION_CONSTANT';
 */
export const CHANGE_PROJECT_NAME = 'CHANGE_PROJECT_NAME';
export const CHANGE_OWNER_NAME = 'CHANGE_OWNER_NAME';
export const CHANGE_TEST = 'CHANGE_TEST';
export const SET_IMPORT_FORM_STATE = 'SET_IMPORT_FORM_STATE';
export const CHANGE_IMPORT_FORM_PMID = 'CHANGE_IMPORT_FORM_PMID';
export const CHANGE_IMPORT_FORM_LOADING_STATE = 'CHANGE_IMPORT_FORM_LOADING_STATE';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const CHANGE_IMPORT_FORM_AUTHORS = 'CHANGE_IMPORT_FORM_AUTHORS';
export const CHANGE_IMPORT_FORM_SELECTED_AFFILIATION = 'CHANGE_IMPORT_FORM_SELECTED_AFFILIATION';

/* article info */
export const CHANGE_IMPORT_FORM_SOURCE = 'CHANGE_IMPORT_FORM_SOURCE';

/* Applicant */
export const CHANGE_IMPORT_FORM_APPLICANT_NAME = 'CHANGE_IMPORT_FORM_APPLICANT_NAME';
export const CHANGE_IMPORT_FORM_APPLICANT_DEPARTMENT = 'CHANGE_IMPORT_FORM_APPLICANT_DEPARTMENT';

export const CHANGE_IMPORT_FORM_APPLICANT_NAME_PINYIN = 'CHANGE_IMPORT_FORM_APPLICANT_NAME_PINYIN';
export const CHANGE_IMPORT_FORM_APPLICANT_DEPARTMENT_PINYIN = 'CHANGE_IMPORT_FORM_APPLICANT_DEPARTMENT_PINYIN';
