/*
 * AppConstants
 * These are the variables that determine what our central data store (reducer.js)
 * changes in our state. When you add a new action, you have to add a new constant here
 *
 * Follow this format:
 * export const YOUR_ACTION_CONSTANT = 'YOUR_ACTION_CONSTANT';
 */

/* Home Constants */
export const UPDATE_RECENT_IMPORT = 'UPDATE_RECENT_IMPORT';
export const UPDATE_RECENT_EXPORT = 'UPDATE_RECENT_EXPORT';

/* Import form */
export const SET_IMPORT_FORM_DATA = 'SET_IMPORT_FORM_DATA';
export const SET_IMPORT_FORM_STATE = 'SET_IMPORT_FORM_STATE';
export const CHANGE_IMPORT_FORM_PMID = 'CHANGE_IMPORT_FORM_PMID';
export const CHANGE_IMPORT_FORM_LOADING_STATE = 'CHANGE_IMPORT_FORM_LOADING_STATE';

export const ADD_NOTIFICATION = 'ADD_NOTIFICATION';
export const REMOVE_NOTIFICATION = 'REMOVE_NOTIFICATION';

export const CHANGE_IMPORT_FORM_AUTHORS = 'CHANGE_IMPORT_FORM_AUTHORS';
export const CHANGE_IMPORT_FORM_SELECTED_AFFILIATION = 'CHANGE_IMPORT_FORM_SELECTED_AFFILIATION';

/* article info */
export const CHANGE_IMPORT_FORM_SOURCE = 'CHANGE_IMPORT_FORM_SOURCE';

/* Applicant */
export const INIT_APPLICANT = {
    department: '',
    applicant: '',
    departmentPinyin: '',
    applicantPinyin: ''
};
export const REMOVE_APPLICANT = 'REMOVE_APPLICANT';
export const ADD_NEW_APPLICANT = 'ADD_NEW_APPLICANT';
export const CHANGE_IMPORT_FORM_APPLICANT_NAME = 'CHANGE_IMPORT_FORM_APPLICANT_NAME';
export const CHANGE_IMPORT_FORM_APPLICANT_DEPARTMENT = 'CHANGE_IMPORT_FORM_APPLICANT_DEPARTMENT';

export const CHANGE_IMPORT_FORM_APPLICANT_NAME_PINYIN = 'CHANGE_IMPORT_FORM_APPLICANT_NAME_PINYIN';
export const CHANGE_IMPORT_FORM_APPLICANT_DEPARTMENT_PINYIN = 'CHANGE_IMPORT_FORM_APPLICANT_DEPARTMENT_PINYIN';

export const CHANGE_IMPORT_FORM_SELECTED_PT = 'CHANGE_IMPORT_FORM_SELECTED_PT';
export const CHANGE_IMPORT_FORM_SELECTED_ISSN = 'CHANGE_IMPORT_FORM_SELECTED_ISSN';

export const CHANGE_IMPORT_FORM_ARTICLE_TITLE = 'CHANGE_IMPORT_FORM_ARTICLE_TITLE';

export const CHANGE_IS_UPDATING_SCI = 'CHANGE_IS_UPDATING_SCI';
export const UPDATE_SCI_TABLE = 'UPDATE_SCI_TABLE';

// Dialogs
export const DISPLAY_DIALOG = 'DISPLAY_DIALOG';

// Dialog selection
export const CHANGE_SELECTED_APPLICANT = 'CHANGE_SELECTED_APPLICANT';
export const CHANGE_SELECTED_SCI = 'CHANGE_SELECTED_SCI';

// Applicant Dialog
export const DISPLAY_APPLICANT_DIALOG = 'DISPLAY_APPLICANT_DIALOG';
export const CHANGE_APPLICANT_DIALOG_WHO = 'CHANGE_APPLICANT_DIALOG_WHO';
